export const ASK_FOR_CPU_DATA = "ASK_FOR_CPU_DATA";
export const CPU_DATA_ARRIVED = "CPU_DATA_ARRIVED";
export const PC_INFO_ARRIVED = "PC_INFO_ARRIVED";
export const CPU_SAMPLE_ARRIVED = "CPU_SAMPLE_ARRIVED";
export const GPU_SAMPLE_ARRIVED = "GPU_SAMPLE_ARRIVED";
export const RAM_SAMPLE_ARRIVED = "RAM_SAMPLE_ARRIVED";

export const COLOR_UPDATED = "COLOR_UPDATED";

export default {
  ASK_FOR_CPU_DATA,
  CPU_DATA_ARRIVED,
  PC_INFO_ARRIVED,
  CPU_SAMPLE_ARRIVED,
  GPU_SAMPLE_ARRIVED,
  RAM_SAMPLE_ARRIVED,
  COLOR_UPDATED,
};
